/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Source = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'snippet' : IDL.Text,
  'favicon' : IDL.Text,
});
export const SearchResult = IDL.Record({
  'model' : IDL.Text,
  'answer' : IDL.Text,
  'sources' : IDL.Vec(Source),
  'followUps' : IDL.Vec(IDL.Text),
});
export const Thread = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'createdAt' : IDL.Int,
  'results' : IDL.Vec(SearchResult),
  'updatedAt' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'createThread' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteThread' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getMyThreads' : IDL.Func([], [IDL.Vec(Thread)], ['query']),
  'getThread' : IDL.Func([IDL.Text], [Thread], ['query']),
  'listThreads' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Thread)], ['query']),
  'search' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SearchResult],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Source = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'snippet' : IDL.Text,
    'favicon' : IDL.Text,
  });
  const SearchResult = IDL.Record({
    'model' : IDL.Text,
    'answer' : IDL.Text,
    'sources' : IDL.Vec(Source),
    'followUps' : IDL.Vec(IDL.Text),
  });
  const Thread = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'createdAt' : IDL.Int,
    'results' : IDL.Vec(SearchResult),
    'updatedAt' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'createThread' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteThread' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getMyThreads' : IDL.Func([], [IDL.Vec(Thread)], ['query']),
    'getThread' : IDL.Func([IDL.Text], [Thread], ['query']),
    'listThreads' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Thread)], ['query']),
    'search' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [SearchResult],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };